[[proxy]]
rewrite = "/api/"
backend = "http://localhost:3000/api/"

[[hooks]]
stage = "build"
command = "sh"
command_arguments = ["-c", "npx @tailwindcss/cli -i input.css -o public/tailwind.css"]

[build]
target = "index.html"
dist = "dist"

[tools]
wasm_opt = "version_117"
